spring:
  application:
    name: server

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 5000MB

  # before AWS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hgcq
    password: yuhan12
    url: jdbc:mysql://localhost:3306/recoder

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info
  file:
    name: recoder.log